name: Deploy to EdgeOne Pages
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: "corepack enable"

      - name: Install step
        run: "yarn install"

      - name: Build step
        run: yarn run build --preset=cloudflare_pages

      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy .output -n ${{ secrets.EDGEONE_PROJECT_NAME }} -t ${{ secrets.EDGEONE_API_TOKEN }}
